// vue_常见方法/src/components/ceshi/ceshi.vue
<template>
 <div class="ceshi">
   <ul>
     <div><input type="text"></div>
     <button @click="show">点击</button>
   </ul>
 </div>
</template>

<script>
  import qs from 'qs'
export default {
  data(){
    return {
      mk:[
        {name:[1,2,3]},
        {name:['sdf',34,58]},
        {name:[1,'就看到',3]}
      ],
      isTruy:false,
      name:{a:'123',b:55}
    }
  },
  methods:{
    show(){
      let m=qs.stringify(this.name);
      console.log(m)
    }
  }
}
</script>
<style lang="scss">
</style>

// React/ant-design-pro-antd-3/src/pages/ceshi/ceshi.tsx
import React, { useEffect, useState } from 'react'
import { Button } from 'antd'

const Ceshi = () => {
    const [count, setCount] = useState(0)
    const [name, setName] = useState('')
    useEffect(()=>{
        console.log(111);
        
    },[count,name])

    useEffect(()=>{
       return (
        ()=>{
            console.log('xizaila');
        }
       )
    },[])

    return (
        <div>
            <div>{count}</div>
            <Button onClick={() => { setCount(count + 1) }}>点击</Button>
            <Button onClick={() => { setName(name + 'a') }}>点击</Button>
        </div>
    )
}

export default Ceshi
